### ISSUE TITLE
Account doesn't open on multiple devices with Kodi instances

### ISSUE THREAD

**Issue by ictforfree** [ddurdle/GDrive-for-KODI#194]
Hi Ddurdle, 

Untill now GDrive for Kodi has always worked perfectly. But just recently opening my account on any of the devices that i own (Raspberry Pi, Laptop & Tablet) displays the "Gdrive error", check the log for more information. Since i'm not a programmer myself, i don't really know what to do with the errors from the logs. But here you go, 

`2019-08-28 10:52:37.537 T:9984  NOTICE: [script.module.clouddrive.common][service-source-9984]: Service 'source' started in port 8585
2019-08-28 10:53:56.882 T:12396   ERROR: CImageLoader::DoWork - Direct texture file loading failed for resource://resource.images.moviegenreicons.transparent/Action & Adventure.png
2019-08-28 10:53:56.890 T:12396   ERROR: CImageLoader::DoWork - Direct texture file loading failed for resource://resource.images.moviegenreicons.transparent/Sci-Fi & Fantasy.png
2019-08-28 10:53:58.847 T:31568   ERROR: Misplaced !
2019-08-28 10:53:58.847 T:31568   ERROR: Error parsing boolean expression string.endswith(listitem.label,!)
2019-08-28 10:54:00.056 T:32804 WARNING: CAddonSettings[plugin.video.gdrive]: failed to parse old setting definition for "user_agent" of type "hidden"
2019-08-28 10:54:00.056 T:32804 WARNING: CAddonSettings[plugin.video.gdrive]: failed to parse old setting definition for "gdrive_numaccounts" of type "integer"
2019-08-28 10:54:01.467 T:32792 WARNING: CAddonSettings[plugin.video.gdrive]: failed to parse old setting definition for "user_agent" of type "hidden"
2019-08-28 10:54:01.468 T:32792 WARNING: CAddonSettings[plugin.video.gdrive]: failed to parse old setting definition for "gdrive_numaccounts" of type "integer"
2019-08-28 10:54:03.134 T:32792 WARNING: CAddonSettings[plugin.video.gdrive]: failed to parse old setting definition for "user_agent" of type "hidden"
2019-08-28 10:54:03.134 T:32792 WARNING: CAddonSettings[plugin.video.gdrive]: failed to parse old setting definition for "gdrive_numaccounts" of type "integer"
2019-08-28 10:54:03.194 T:32792 WARNING: CAddonSettings[plugin.video.gdrive]: failed to parse old setting definition for "user_agent" of type "hidden"
2019-08-28 10:54:03.194 T:32792 WARNING: CAddonSettings[plugin.video.gdrive]: failed to parse old setting definition for "gdrive_numaccounts" of type "integer"
2019-08-28 10:54:03.741 T:32792   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "C:\Users\pepij\AppData\Roaming\Kodi\addons\plugin.video.gdrive\default.py", line 23, in <module>
                                                mediaEngine.run()
                                              File "C:\Users\pepij\AppData\Roaming\Kodi\addons\plugin.video.gdrive\resources\lib\engine.py", line 1442, in run
                                                service.addDirectory(folder.folder(drive.id,'['+addon.getLocalizedString(30200) + ' - ' + str(drive.title)+']', isRoot=True), contextType=contextType, encfs=False )
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
                                            -->End of Python script error report<--
2019-08-28 10:54:03.819 T:5100   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.gdrive/?content_type=video&instance=gdrive1&mode=main
2019-08-28 10:54:03.834 T:31568   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.gdrive/?content_type=video&instance=gdrive1&mode=main) failed
2019-08-28 10:54:04.064 T:26116 WARNING: CAddonSettings[plugin.video.gdrive]: failed to parse old setting definition for "user_agent" of type "hidden"
2019-08-28 10:54:04.064 T:26116 WARNING: CAddonSettings[plugin.video.gdrive]: failed to parse old setting definition for "gdrive_numaccounts" of type "integer"
2019-08-28 10:54:06.663 T:31552 WARNING: CAddonSettings[plugin.video.gdrive]: failed to parse old setting definition for "user_agent" of type "hidden"
2019-08-28 10:54:06.663 T:31552 WARNING: CAddonSettings[plugin.video.gdrive]: failed to parse old setting definition for "gdrive_numaccounts" of type "integer"
2019-08-28 10:54:07.207 T:31552   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "C:\Users\pepij\AppData\Roaming\Kodi\addons\plugin.video.gdrive\default.py", line 23, in <module>
                                                mediaEngine.run()
                                              File "C:\Users\pepij\AppData\Roaming\Kodi\addons\plugin.video.gdrive\resources\lib\engine.py", line 1442, in run
                                                service.addDirectory(folder.folder(drive.id,'['+addon.getLocalizedString(30200) + ' - ' + str(drive.title)+']', isRoot=True), contextType=contextType, encfs=False )
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
                                            -->End of Python script error report<--
2019-08-28 10:54:07.276 T:32384   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.gdrive/?content_type=video&instance=gdrive1&mode=main
2019-08-28 10:54:07.283 T:31568   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.gdrive/?content_type=video&instance=gdrive1&mode=main) failed
2019-08-28 10:54:07.458 T:30572 WARNING: CAddonSettings[plugin.video.gdrive]: failed to parse old setting definition for "user_agent" of type "hidden"
2019-08-28 10:54:07.458 T:30572 WARNING: CAddonSettings[plugin.video.gdrive]: failed to parse old setting definition for "gdrive_numaccounts" of type "integer"
`

Do you have any idea why this happens? 

Thanks in advance.

**Comment by ictforfree** [comment]
It seems to have fixed itself. 

Closed issue due to problem fixed
